/*
 * Copyright 2017-2026 original authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.micronaut.langchain4j.agentic.structuredoutput;

import dev.langchain4j.data.message.AiMessage;
import dev.langchain4j.model.chat.Capability;
import dev.langchain4j.model.chat.ChatModel;
import dev.langchain4j.model.chat.request.ChatRequest;
import dev.langchain4j.model.chat.request.json.JsonArraySchema;
import dev.langchain4j.model.chat.request.json.JsonIntegerSchema;
import dev.langchain4j.model.chat.request.json.JsonObjectSchema;
import dev.langchain4j.model.chat.request.json.JsonSchema;
import dev.langchain4j.model.chat.response.ChatResponse;
import io.micronaut.context.ApplicationContext;
import io.micronaut.context.annotation.Requires;
import jakarta.inject.Singleton;
import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.atomic.AtomicReference;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertNull;

/**
 * Agents returning types annotated with {@code @JsonSchema} send the schemas generated by Micronaut JSON Schema.
 */
class StructuredOutputAgentTest {

    static final String ENV = "structured-output";

    @Test
    void agentSendsTheGeneratedSchema() {
        try (ApplicationContext context = ApplicationContext.run(ENV)) {
            Itinerary itinerary = context.getBean(TripPlannerAgent.class).plan("Antwerp");

            assertEquals(new Itinerary("Antwerp", List.of(new Stop("Cathedral", 60))), itinerary);
            JsonSchema schema = context.getBean(RecordingChatModel.class).lastRequest().responseFormat().jsonSchema();
            assertEquals("Itinerary", schema.name());
            JsonObjectSchema root = (JsonObjectSchema) schema.rootElement();
            assertEquals("A trip itinerary.", root.description());
            assertEquals("The places to visit, in order", root.properties().get("stops").description());
            JsonObjectSchema stop = (JsonObjectSchema) ((JsonArraySchema) root.properties().get("stops")).items();
            assertEquals("A place of an itinerary.", stop.description());
            assertInstanceOf(JsonIntegerSchema.class, stop.properties().get("minutes"));
            assertEquals("How long to stay there", stop.properties().get("minutes").description());
        }
    }

    @Test
    void agentSendsTheGeneratedSchemaOfListElements() {
        try (ApplicationContext context = ApplicationContext.run(ENV)) {
            List<Stop> stops = context.getBean(StopPickerAgent.class).pick("Antwerp");

            assertEquals(List.of(new Stop("Cathedral", 60)), stops);
            JsonSchema schema = context.getBean(RecordingChatModel.class).lastRequest().responseFormat().jsonSchema();
            assertEquals("List_of_Stop", schema.name());
            JsonArraySchema values = (JsonArraySchema) ((JsonObjectSchema) schema.rootElement()).properties().get("values");
            assertEquals("A place of an itinerary.", values.items().description());
        }
    }

    @Test
    void agentsWithTheirOwnModelKeepTheReflectiveSchema() {
        try (ApplicationContext context = ApplicationContext.run(ENV)) {
            assertEquals("Antwerp", context.getBean(SuppliedModelAgent.class).plan("Antwerp").city());

            JsonObjectSchema root = (JsonObjectSchema) SuppliedModelAgent.MODEL.lastRequest().responseFormat().jsonSchema().rootElement();
            assertNull(root.description());
        }
    }

    @Singleton
    @Requires(env = ENV)
    static final class RecordingChatModel implements ChatModel {

        private static final Map<String, String> ANSWERS = Map.of(
            "Itinerary", "{\"city\": \"Antwerp\", \"stops\": [{\"name\": \"Cathedral\", \"minutes\": 60}]}",
            "List_of_Stop", "{\"values\": [{\"name\": \"Cathedral\", \"minutes\": 60}]}"
        );

        private final AtomicReference<ChatRequest> lastRequest = new AtomicReference<>();

        @Override
        public ChatResponse doChat(ChatRequest chatRequest) {
            lastRequest.set(chatRequest);
            String answer = ANSWERS.get(chatRequest.responseFormat().jsonSchema().name());
            return ChatResponse.builder().aiMessage(AiMessage.from(answer)).build();
        }

        @Override
        public Set<Capability> supportedCapabilities() {
            return Set.of(Capability.RESPONSE_FORMAT_JSON_SCHEMA);
        }

        ChatRequest lastRequest() {
            return lastRequest.get();
        }
    }
}
