package example.micronaut.graal;

import dev.langchain4j.agentic.Agent;
import dev.langchain4j.agentic.declarative.Output;
import dev.langchain4j.agentic.declarative.ParallelAgent;
import dev.langchain4j.agentic.declarative.SequenceAgent;
import dev.langchain4j.service.UserMessage;
import dev.langchain4j.service.V;
import io.micronaut.langchain4j.agentic.annotation.AgenticService;
import io.micronaut.test.extensions.junit5.annotation.MicronautTest;
import jakarta.inject.Inject;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 * Agentic services, their sub-agents and workflows work in a native image with the metadata generated by
 * micronaut-langchain4j-processor only.
 */
@MicronautTest(startApplication = false)
class NativeAgenticServiceTest {

    @Inject
    GreeterAgent greeter;

    @Inject
    StoryWorkflow story;

    @Inject
    PlanWorkflow plan;

    @Test
    void agent() {
        assertEquals("Say hello to Fred", greeter.greet("Fred"));
    }

    @Test
    void sequence() {
        assertEquals("Write about Write a title for dragons", story.write("dragons"));
    }

    @Test
    void parallelWithStaticOutput() {
        assertEquals("Pick music for jazz + Pick a menu for romantic", plan.plan("jazz", "romantic"));
    }

    @AgenticService
    public interface GreeterAgent {
        @UserMessage("Say hello to {{name}}")
        @Agent(description = "Greets a person by name")
        String greet(@V("name") String name);
    }

    // sub-agents without @AgenticService
    public interface TitleAgent {
        @UserMessage("Write a title for {{topic}}")
        @Agent(outputKey = "title")
        String title(@V("topic") String topic);
    }

    public interface WriterAgent {
        @UserMessage("Write about {{title}}")
        @Agent(outputKey = "story")
        String write(@V("title") String title);
    }

    @AgenticService(outputKey = "story")
    public interface StoryWorkflow {
        @SequenceAgent(subAgents = {TitleAgent.class, WriterAgent.class}, outputKey = "story")
        String write(@V("topic") String topic);
    }

    public interface MusicAgent {
        @UserMessage("Pick music for {{style}}")
        @Agent(outputKey = "music")
        String music(@V("style") String style);
    }

    public interface MenuAgent {
        @UserMessage("Pick a menu for {{mood}}")
        @Agent(outputKey = "menu")
        String menu(@V("mood") String mood);
    }

    @AgenticService(outputKey = "plan")
    public interface PlanWorkflow {
        @ParallelAgent(subAgents = {MusicAgent.class, MenuAgent.class}, outputKey = "plan")
        String plan(@V("style") String style, @V("mood") String mood);

        @Output
        static String output(@V("music") String music, @V("menu") String menu) {
            return music + " + " + menu;
        }
    }
}
