package example.micronaut.graal;

import dev.langchain4j.agent.tool.P;
import dev.langchain4j.agent.tool.Tool;
import dev.langchain4j.service.SystemMessage;
import dev.langchain4j.service.UserMessage;
import dev.langchain4j.service.V;
import io.micronaut.langchain4j.annotation.AiService;
import io.micronaut.test.extensions.junit5.annotation.MicronautTest;
import jakarta.inject.Inject;
import jakarta.inject.Singleton;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;

import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 * AI services and tools work in a native image with the metadata generated by micronaut-langchain4j-processor only.
 */
@MicronautTest(startApplication = false)
class NativeAiServiceTest {

    @Inject
    Friend friend;

    @Inject
    CompanyBot bot;

    @Test
    void systemAndUserMessageTemplates() {
        assertEquals("You are a good friend.|Say hello to Fred", friend.chat("Fred"));
    }

    @Test
    void tools() {
        assertEquals("tool:\"2013-03-09\"", bot.ask("When was the PRIVACY document updated?"));
    }

    @AiService
    public interface Friend {
        @SystemMessage("You are a good friend.")
        @UserMessage("Say hello to {{name}}")
        String chat(@V("name") String name);
    }

    @AiService(tools = LegalDocumentTools.class)
    public interface CompanyBot {
        String ask(String question);
    }

    @Singleton
    public static class LegalDocumentTools {
        @Tool("Returns the last time a document was updated")
        public LocalDate lastUpdate(@P("The document") String document) {
            return "privacy".equals(document) ? LocalDate.of(2013, 3, 9) : LocalDate.of(2020, 1, 1);
        }
    }
}
