package example.micronaut.graal;

import io.micronaut.test.extensions.junit5.annotation.MicronautTest;
import jakarta.inject.Inject;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 * A human-in-the-loop sub-agent, which LangChain4j finds by reading the methods of its type reflectively, works in a
 * native image with the metadata generated by micronaut-langchain4j-processor only.
 */
@MicronautTest(startApplication = false)
class NativeHumanInTheLoopTest {

    @Inject
    PitchWorkflow workflow;

    @Test
    void humanInTheLoop() {
        assertEquals("Pitch dragons to kids", workflow.pitch("dragons"));
    }
}
