plugins {
    id 'io.micronaut.build.internal.langchain4j-base'
    id "io.micronaut.build.internal.module"
}
ossIndexAudit {
    excludeVulnerabilityIds = [
            'CVE-2025-22227', // https://ossindex.sonatype.org/vulnerability/CVE-2025-22227?component-type=maven&component-name=io.projectreactor.netty%2Freactor-netty-http
    ]
}

micronautBuild {
    binaryCompatibility.baselineVersion = '2.0.0-M1'
}

dependencies {
    annotationProcessor(mn.micronaut.inject.java)
    api(platform(libs.boms.langchain4j))
    implementation(platform(libs.boms.langchain4j))
    testAnnotationProcessor(mn.micronaut.inject.java)
    testImplementation(mnTest.micronaut.test.junit5)
    testRuntimeOnly(mnLogging.logback.classic)
    testRuntimeOnly(mnTest.junit.jupiter.engine)
    testImplementation(platform(mnTest.boms.testcontainers))
    testImplementation(libs.junit.platform.engine)
}
