plugins {
    id("io.micronaut.build.internal.langchain4j-module")
    id "io.micronaut.build.internal.java-base"
}

dependencies {
    annotationProcessor(projects.micronautLangchain4jProcessor)
    annotationProcessor(mnSourcegen.micronaut.sourcegen.generator.java)
    api(projects.micronautLangchain4jCore)
    testImplementation(projects.testSuiteChatmodelTck)
}
