plugins {
    id 'io.micronaut.build.internal.langchain4j-base'
    id "io.micronaut.build.internal.module"
    id("org.sonatype.gradle.plugins.scan")
}
String ossIndexUsername = System.getenv("OSS_INDEX_USERNAME") ?: project.properties["ossIndexUsername"]
String ossIndexPassword = System.getenv("OSS_INDEX_PASSWORD") ?: project.properties["ossIndexPassword"]
boolean sonatypePluginConfigured = ossIndexUsername != null && ossIndexPassword != null
ossIndexAudit {
if (sonatypePluginConfigured) {
    username = ossIndexUsername
    password = ossIndexPassword
}
    excludeVulnerabilityIds = [
            'CVE-2025-22227', // https://ossindex.sonatype.org/vulnerability/CVE-2025-22227?component-type=maven&component-name=io.projectreactor.netty%2Freactor-netty-http
    ]
}

dependencies {
    annotationProcessor(mn.micronaut.inject.java)
    api(platform(libs.langchain4j.bom))
    implementation(platform(libs.langchain4j.bom))
    testAnnotationProcessor(mn.micronaut.inject.java)
    testImplementation(mnTest.micronaut.test.junit5)
    testRuntimeOnly(mnLogging.logback.classic)
    testRuntimeOnly(mnTest.junit.jupiter.engine)
    testImplementation(libs.junit.platform.engine)
}

