/*
 * Copyright 2017-2026 original authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.micronaut.langchain4j.jsonschema;

import io.micronaut.context.annotation.ConfigurationProperties;
import io.micronaut.core.util.Toggleable;
import org.jspecify.annotations.Nullable;

/**
 * Configuration of the structured outputs backed by generated JSON schemas.
 *
 * @since 2.4.0
 */
@ConfigurationProperties(StructuredOutputConfiguration.PREFIX)
public final class StructuredOutputConfiguration implements Toggleable {

    public static final String PREFIX = "langchain4j.structured-output";

    public static final boolean DEFAULT_ENABLED = true;

    private boolean enabled = DEFAULT_ENABLED;

    @Nullable
    private Boolean forceJsonSchemaResponseFormat;

    @Override
    public boolean isEnabled() {
        return enabled;
    }

    /**
     * Whether the JSON schemas supplied by {@link StructuredOutputSchemaProvider} beans (for example generated by
     * Micronaut JSON Schema) replace the schemas LangChain4j derives reflectively. Default value {@value #DEFAULT_ENABLED}.
     *
     * @param enabled Whether generated schemas are used
     */
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * @return Whether the JSON schema response format is sent to models that do not declare the capability
     */
    @Nullable
    public Boolean getForceJsonSchemaResponseFormat() {
        return forceJsonSchemaResponseFormat;
    }

    /**
     * Whether services returning a type with a generated schema send it as the JSON schema response format to chat
     * models that do not declare {@code RESPONSE_FORMAT_JSON_SCHEMA}, instead of appending format instructions to the
     * user message. When not set, it is done for the models of the providers known to accept it (see
     * {@link JsonSchemaResponseFormatSupport}), such as Google AI Gemini.
     *
     * @param forceJsonSchemaResponseFormat Whether the response format is forced
     */
    public void setForceJsonSchemaResponseFormat(@Nullable Boolean forceJsonSchemaResponseFormat) {
        this.forceJsonSchemaResponseFormat = forceJsonSchemaResponseFormat;
    }
}
