plugins {
    id("io.micronaut.build.internal.langchain4j-module")
}

dependencies {
    api(mn.micronaut.context)
    api(libs.langchain4j)
    api(libs.langchain4j.http.client)
    implementation(platform(mnReactor.boms.reactor))
    implementation(mn.micronaut.http.client.core)
    implementation(libs.reactor.core)
    // structured outputs use the JSON schemas generated by Micronaut JSON Schema when it is on the classpath
    compileOnly(mnJsonSchema.micronaut.json.schema.utils)
    testAnnotationProcessor(mn.micronaut.inject.java)
    testAnnotationProcessor(mnJsonSchema.micronaut.json.schema.processor)
    testImplementation(mnJsonSchema.micronaut.json.schema.utils)
    testImplementation(mn.micronaut.http.server.netty)
    testImplementation(mn.micronaut.jackson.databind)
    testImplementation(libs.langchain4j.ollama)
    testImplementation(mnTest.micronaut.test.junit5)
    testRuntimeOnly(mn.micronaut.http.client)
    testRuntimeOnly(mnLogging.logback.classic)
    testRuntimeOnly(mnTest.junit.jupiter.engine)
}
