/*
 * Copyright 2017-2026 original authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.micronaut.langchain4j.jsonschema;

import dev.langchain4j.model.chat.Capability;
import dev.langchain4j.model.chat.request.ChatRequest;
import dev.langchain4j.model.chat.request.json.JsonArraySchema;
import dev.langchain4j.model.chat.request.json.JsonEnumSchema;
import dev.langchain4j.model.chat.request.json.JsonIntegerSchema;
import dev.langchain4j.model.chat.request.json.JsonObjectSchema;
import dev.langchain4j.model.chat.request.json.JsonReferenceSchema;
import dev.langchain4j.model.chat.request.json.JsonSchema;
import dev.langchain4j.model.chat.request.json.JsonSchemaElement;
import dev.langchain4j.model.chat.request.json.JsonStringSchema;
import dev.langchain4j.service.output.JsonSchemas;
import io.micronaut.context.annotation.Factory;
import io.micronaut.context.annotation.Property;
import io.micronaut.context.annotation.Requires;
import io.micronaut.langchain4j.annotation.AiService;
import io.micronaut.langchain4j.jsonschema.StructuredOutputTypes.Category;
import io.micronaut.langchain4j.jsonschema.StructuredOutputTypes.Level;
import io.micronaut.langchain4j.jsonschema.StructuredOutputTypes.Plain;
import io.micronaut.langchain4j.jsonschema.StructuredOutputTypes.PlannedDay;
import io.micronaut.langchain4j.jsonschema.StructuredOutputTypes.PlannedTalk;
import io.micronaut.test.extensions.junit5.annotation.MicronautTest;
import jakarta.inject.Inject;
import jakarta.inject.Singleton;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Map;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * An {@code @AiService} returning types annotated with {@code @JsonSchema} sends the schemas generated by
 * Micronaut JSON Schema as the response format.
 */
@MicronautTest(startApplication = false)
@Property(name = "spec.name", value = StructuredOutputAiServiceTest.SPEC_NAME)
class StructuredOutputAiServiceTest {

    static final String SPEC_NAME = "StructuredOutputAiServiceTest";

    @Inject
    SchemaRecordingChatModel chatModel;

    @Inject
    GeneratedJsonSchemaProvider provider;

    @Test
    void sendsTheGeneratedSchema(Planner planner) throws IOException {
        PlannedDay day = planner.planDay("Monday");

        assertEquals("Monday", day.day());
        assertEquals(Level.ADVANCED, day.talks().getFirst().level());

        JsonSchema schema = chatModel.lastRequest().responseFormat().jsonSchema();
        assertEquals("PlannedDay", schema.name());
        assertEquals(provider.findSchema(PlannedDay.class).orElseThrow(), schema.rootElement());

        JsonObjectSchema root = (JsonObjectSchema) schema.rootElement();
        assertEquals("The talks planned for a day.", root.description());
        assertEquals(Set.of("day", "talks"), root.properties().keySet());
        assertEquals("The talks, in chronological order", root.properties().get("talks").description());

        // the referenced schema of PlannedTalk, generated in another file, is inlined
        JsonObjectSchema talk = (JsonObjectSchema) ((JsonArraySchema) root.properties().get("talks")).items();
        assertEquals("A talk chosen for the schedule.", talk.description());
        assertEquals(Set.of("talkId", "title", "reason", "level", "tags"), talk.properties().keySet());
        assertEquals(List.of("talkId"), talk.required());
        assertInstanceOf(JsonIntegerSchema.class, talk.properties().get("talkId"));
        assertEquals("The identifier of the talk", talk.properties().get("talkId").description());
        assertEquals(List.of("BEGINNER", "ADVANCED"), ((JsonEnumSchema) talk.properties().get("level")).enumValues());
        assertInstanceOf(JsonStringSchema.class, ((JsonArraySchema) talk.properties().get("tags")).items());

        // the schema matches the generated document rather than the one LangChain4j derives reflectively
        assertTrue(generatedSchema("structured-output-types-planned-day").contains("\"description\":\"The talks planned for a day.\""));
        JsonSchemaElement reflective = JsonSchemas.jsonSchemaFrom(PlannedDay.class).orElseThrow().rootElement();
        assertTrue(reflective.description() == null || !reflective.description().equals(root.description()));
    }

    @Test
    void sendsTheGeneratedSchemaOfListElements(Planner planner) {
        List<PlannedTalk> talks = planner.pickTalks("Java");

        assertEquals(1, talks.size());
        assertEquals("Records", talks.getFirst().title());

        JsonSchema schema = chatModel.lastRequest().responseFormat().jsonSchema();
        assertEquals("List_of_PlannedTalk", schema.name());
        JsonObjectSchema root = (JsonObjectSchema) schema.rootElement();
        assertEquals(List.of("values"), root.required());
        JsonArraySchema values = (JsonArraySchema) root.properties().get("values");
        assertEquals(provider.findSchema(PlannedTalk.class).orElseThrow(), values.items());
    }

    @Test
    void recursiveSchemasUseDefinitions(Planner planner) {
        Category category = planner.categorize("Java");

        assertEquals("Java", category.name());
        assertEquals("Records", category.children().getFirst().name());

        JsonObjectSchema root = (JsonObjectSchema) chatModel.lastRequest().responseFormat().jsonSchema().rootElement();
        assertEquals("A category and its sub-categories.", root.description());
        String reference = ((JsonReferenceSchema) ((JsonArraySchema) root.properties().get("children")).items()).reference();
        JsonObjectSchema definition = (JsonObjectSchema) root.definitions().get(reference);
        assertEquals(root.properties(), definition.properties());
    }

    @Test
    void typesWithoutGeneratedSchemaKeepTheReflectiveSchema(Planner planner) {
        assertEquals("plain", planner.plain("plain").value());

        ChatRequest request = chatModel.lastRequest();
        assertEquals(JsonSchemas.jsonSchemaFrom(Plain.class).orElseThrow(), request.responseFormat().jsonSchema());
    }

    @Requires(property = "spec.name", value = SPEC_NAME)
    @AiService
    interface Planner {
        PlannedDay planDay(String day);

        List<PlannedTalk> pickTalks(String topic);

        Category categorize(String topic);

        Plain plain(String value);
    }

    @Factory
    @Requires(property = "spec.name", value = SPEC_NAME)
    static final class TestBeans {

        @Singleton
        SchemaRecordingChatModel chatModel() {
            return new SchemaRecordingChatModel(Set.of(Capability.RESPONSE_FORMAT_JSON_SCHEMA), answers());
        }
    }

    static String generatedSchema(String name) throws IOException {
        try (InputStream schema = StructuredOutputAiServiceTest.class.getResourceAsStream("/META-INF/schemas/" + name + ".schema.json")) {
            return new String(schema.readAllBytes(), StandardCharsets.UTF_8);
        }
    }

    static Map<String, String> answers() {
        String talk = """
            {"talkId": 1, "title": "Records", "reason": "Modern Java", "level": "ADVANCED", "tags": ["java"]}""";
        return Map.of(
            "PlannedDay", "{\"day\": \"Monday\", \"talks\": [" + talk + "]}",
            "List_of_PlannedTalk", "{\"values\": [" + talk + "]}",
            "Category", "{\"name\": \"Java\", \"children\": [{\"name\": \"Records\", \"children\": []}]}",
            "Plain", "{\"value\": \"plain\"}"
        );
    }
}
